services:
  - type: web
    name: cloud-storage-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: "yoursecretkeyhere"
